# Generated by Django 5.2.4 on 2025-08-04 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', 'order', '-created_date']},
        ),
        migrations.AddField(
            model_name='project',
            name='achievements',
            field=models.TextField(blank=True, help_text='Logros específicos del proyecto (separados por líneas)'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_app', 'Aplicación Web'), ('api', 'API REST'), ('automation', 'Automatización'), ('iot', 'IoT'), ('other', 'Otro')], default='web_app', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Marcar como proyecto destacado'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Orden de visualización (menor número = primero)'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, help_text='Descripción corta para preview', max_length=150),
        ),
    ]
