# Generated by Django 5.2.4 on 2025-08-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, help_text="Path to static image (e.g., 'img/calculadora.PNG')", max_length=255, null=True),
        ),
    ]
